Revert "StatusBarIconController: Ensure battery text view is tinted as well"
ERROR: /home/simao/sthdd/data/jenkins/workspace/halogenOS/xos/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBarIconController.java:149: The method findViewbyId(int) is undefined for the type View

This reverts commit 3ff63f45f255658f3c56eb85eca1eb3156389cff.

Change-Id: Ie0b1febbbbbae56641fe24402b39f54ce7789d50